# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

# 项目名称
project = 'QuecPigeon Docs'

# 版权信息
copyright = '2021 - 2023, ThinkCloud & 洛霜'

# 作者
author = 'Exdream'

# The full version, including alpha/beta/rc tags
# 版本号
release = '0.0.1'

# 大版本
version = '0.0.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinxcontrib.mermaid",    # 渲染 mermaid 流程图
    # "sphinx.ext.autodoc",     # 自动通过源码生成 API 文档
    "sphinx_copybutton",        # 显示代码复制按钮
    "sphinx_design",            # 强大的页面设计工具，但是会破坏文档通用性，有移植需求的文档不建议开启
    # "sphinx_togglebutton",    # 给文档加入点击后展开的隐藏段落
    # "sphinx.ext.todo",        # 对待办列表功能的支持
    "sphinx.ext.mathjax",       # 对数学公式的支持
    "sphinx-mathjax-offline"    # 离线加载数学公式
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# 默认语言
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# 页面主题
html_theme = 'sphinx_book_theme'

# 网站标题
html_title = "QuecPython 从入门到入土"
# 网站 logo
html_logo = "./media/qpg-logo.png"
# favicon 图标
html_favicon = "./media/logo.ico"

# 不懂干啥用的，官方也没写
html_copy_source = True
html_sourcelink_suffix = ""

# 在 footer 处显示文档更新时间
html_last_updated_fmt = ""

html_theme_options = {
    # 源码托管商（1.0 主题中添加，只支持 gitlab/github/bitbucket）
    # "repository_provider": "github",
    # 文档源码
    "repository_url": "https://github.com/thinkcloud-exdream/QuecPigeon-Docs",
    # 源码分支和源码在库中的路径
    "repository_branch": "main",
    # "path_to_docs": ".",
    # 显示源码按钮（1.0 主题中添加）
    # "use_source_button": True,
    # 显示 GitHub 按钮
    "use_repository_button": True,
    # 显示下载文档按钮
    "use_download_button": True,
    # 显示全屏按钮
    "use_fullscreen_button": True,
    # 在左侧栏显示主页链接
    "home_page_in_toc": False,
    # 在左上角不显示网站名（该选项在 1.0 版本主题中已被废弃）
    "logo_only": True,
    # 左侧栏默认展开深度
    "show_navbar_depth": 1,
    # 公告栏内容
    "announcement": "An apple a day, keeps the doctor away.",
    # 右侧栏的固定标题
    "toc_title": "文档内容",
    # footer 附加内容，如备案号
    "extra_footer": "<div><a href='https://beian.miit.gov.cn/' target='_blank'>苏ICP备20023496号-2</a></div>"
}




# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# mermaid 流程图插件配置

# 留空，这样能保证从本地获取 js，而不是 cdn
mermaid_version = ""

# 渲染模式：实时原生
mermaid_output_format = "raw"



# 把需要用到的 js 文件包含进去，相对 _static 文件夹的路径
# 注意这里的内容会直接贴在 html 路径上，所以不要使用 ./ 等
html_js_files = [
    'js/mermaid.js',
    'js/mermaid.min.js'
]
